version: '3.8'

services:
  ai-module:
    build: ./ai-module
    container_name: ai-module
    volumes:
      - ./ai-module:/app

  user-service:
    build: ./user-service
    ports:
      - "5001:5000"

  product-service:
    build: ./product-service
    ports:
      - "5002:5000"

  order-service:
    build: ./order-service
    ports:
      - "5003:5000"

  payment-service:
    build: ./payment-service
    ports:
      - "5004:5000"
